name: Build Flutter APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract ZIP File
        run: unzip -o dana_notif_prank.zip -d ./

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Run Flutter Build
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter pub get
            flutter build apk --release
          else
            cd $(find . -maxdepth 2 -name "pubspec.yaml" -exec dirname {} \;)
            flutter pub get
            flutter build apk --release
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
